# Change these first
owner: recylink-status # Your GitHub organization or username, where this repository lives
repo: lollapalooza # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

sites:
  - name: Dashboard Lollapalooza
    url: https://lollapalooza.recylink.com/
    method: GET
  - name: Admin Lollapalooza
    url: https://admin-lollapalooza.recylink.com/login
    method: GET
  - name: API Lollapalooza
    url: https://api-lollapalooza.recylink.com/v1/health
    method: GET
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  favicon: https://www.recylink.com/favicon-32x32.png
  theme: dark
  baseUrl: /lollapalooza
  logoUrl: https://raw.githubusercontent.com/recylink-status/lollapalooza/master/assets/logo-recylink.png
  name: Recylink
  introTitle: "Uptime check for Lollapalooza apps"
  introMessage: real-time status
  navbar:
    - title: Home
      href: /lollapalooza
    - title: Dashboard
      href: https://lollapalooza.recylink.com/  
    - title: Admin
      href: https://admin-lollapalooza.recylink.com/login  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
