# Change these first
owner: recylink-status # Your GitHub organization or username, where this repository lives
repo: lollapalooza # The name of this repository

sites:
  - name: Dashboard Lollapalooza
    url: https://lollapalooza.recylink.com/
    method: GET
  - name: Admin Lollapalooza
    url: https://admin-lollapalooza.recylink.com/login
    method: GET
  - name: API Lollapalooza
    url: https://api-lollapalooza.recylink.com/v1/health
    method: GET
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: /uptimelolla
  logoUrl: https://raw.githubusercontent.com/rodrigoreyesrecylink/uptimelolla/master/assets/LOGO-RECYLINK-2018-COLOR-300x83.png
  name: Uptime Check Lollapalooza Apps
  introTitle: "Uptime Check page for Lollapalooza Apps"
  introMessage: This is a sample status page which uses **real-time** data from Recylink
  navbar:
    - title: Home
      href: /lollapalooza

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
